# Generated by Django 5.2.5 on 2025-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=201013, max_length=6),
            preserve_default=False,
        ),
    ]
